### ISSUE TITLE
当从旧版本迁移后，插件启动时报错

### ISSUE THREAD

**Issue by KafCoppelia** [noneplugin/nonebot-plugin-chatrecorder#15]
```
03-28 10:14:18 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 254, in _handle_exception
    raise error
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: duplicate column name: bot_type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/nonebot_plugin_datastore/db.py", line 87, in init_db
    await run_upgrade()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/nonebot_plugin_datastore/script/utils.py", line 120, in run_upgrade
    await upgrade(config, "head")
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/nonebot_plugin_datastore/script/command.py", line 245, in upgrade
    await run_migration()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/nonebot_plugin_datastore/script/utils.py", line 108, in run_migration
    await connection.run_sync(do_run_migrations, plugin_name)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 787, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/nonebot_plugin_datastore/script/utils.py", line 100, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/nonebot_plugin_chatrecorder/migrations/7228a3a08576_ob12.py", line 58, in upgrade
    op.add_column(
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/alembic/operations/ops.py", line 2044, in add_column
    return operations.invoke(op)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/alembic/operations/base.py", line 401, in invoke
    return fn(self, operation)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 154, in add_column
    operations.impl.add_column(table_name, column, schema=schema, **kw)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/alembic/ddl/impl.py", line 322, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1526, in _execute_ddl
    ret = self._execute_context(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 254, in _handle_exception
    raise error
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/aquabot-beHDLH46-py3.10/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: bot_type
[SQL: ALTER TABLE nonebot_plugin_chatrecorder_messagerecord ADD COLUMN bot_type VARCHAR(64)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

03-28 10:14:18 [ERROR] uvicorn | Application startup failed. Exiting.
```

不知道是否和我手动编译并运行的Python有关系。我在编译Python时添加了如下编译选项：

```
--enable-loadable-sqlite-extensions
```

**Comment by he0119** [comment]
你这是迁移失败了吧。你可以打开数据库把 `bot_type`, `bot_id`, `guild_id`, `channel_id` 这几个字段删除之后，重新迁移试试。

直接运行 `nb datastore upgrade` 来迁移，防止其他插件干扰。

**Comment by KafCoppelia** [comment]
直接运行 `nb datastore upgrade` 报错：

```
<string>:14: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
Usage:  [OPTIONS] COMMAND [ARGS]...
Try ' --help' for help.

Error: No such command 'install'.
```

直接打开数据库修改不是很方便，我再试试

**Comment by he0119** [comment]
> 修改数据库超出能力范围了呃呃呃

推荐使用 `DB Browser for SQLite` 简单直观。

**Comment by KafCoppelia** [comment]
去掉这些之后，启动插件可以正常运行了。这个工具对小白挺好用的
