### ISSUE TITLE
执行迁移命令后失败

### ISSUE THREAD

**Issue by bingqiu456** [noneplugin/nonebot-plugin-chatrecorder#36]
报错如下
```bash
<string>:18: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
Traceback (most recent call last):
  File "<string>", line 24, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_orm\__main__.py", line 281, in main
    orm(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_orm\__main__.py", line 86, in wrapper
    return f(ctx.obj, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_orm\__main__.py", line 173, in upgrade
    return migrate.upgrade(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_orm\migrate.py", line 627, in upgrade
    script.run_env()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\alembic\script\base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 84, in <module>
    await_fallback(run_migrations_online())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 141, in await_fallback
    loop = get_event_loop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 260, in get_event_loop
    return asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
sys:1: RuntimeWarning: coroutine 'run_migrations_online' was never awaited
```
第一次使用该插件
我在cmd里执行了`nb orm upgrade`后发生错误

**Comment by MeetWq** [comment]
应该不是这个插件的问题，看有没有别的用到 `nonebot-plugin-orm` 的插件

**Comment by MeetWq** [comment]
https://github.com/nonebot/plugin-orm/issues/10
