### ISSUE TITLE
可以将数据导出吗

### ISSUE THREAD

**Issue by Xian0Grem** [noneplugin/nonebot-plugin-chatrecorder#59]
我原本NoneBot丢了,但是我数据库还在
我重新建了一个NoneBot
有办法迁移数据过去吗
我尝试过直接把db.sqlite3直接搬过去，但是会报错,下面是报错内容

10-18 02:06:09 [ERROR] uvicorn | Traceback (most recent call last):
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\base.py", line 254, in _catch_revision_errors
    yield
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\base.py", line 317, in get_revisions
    self.revision_map.get_revisions(id_),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\revision.py", line 542, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\revision.py", line 542, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\revision.py", line 565, in get_revisions
    return tuple(
           ^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\revision.py", line 566, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\revision.py", line 637, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '96ced46e72e9'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 84, in init_orm
    await greenlet_spawn(migrate.check, alembic_config)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot_plugin_orm\migrate.py", line 567, in check
    script.run_env()
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\NoneBot\nonebot_liyu\liyu\migrations\env.py", line 90, in <module>
    await_only(coro)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\migrations\env.py", line 79, in run_migrations_online
    await connection.run_sync(do_run_migrations)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 886, in run_sync
    return await greenlet_spawn(
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\migrations\env.py", line 69, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\runtime\environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\runtime\migration.py", line 616, in run_migrations
    for step in self._migrations_fn(heads, self):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot_plugin_orm\migrate.py", line 552, in retrieve_migrations
    if set(script.get_revisions(rev)) != set(script.get_revisions("heads")):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\base.py", line 314, in get_revisions
    with self._catch_revision_errors():
  File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\alembic\script\base.py", line 286, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '96ced46e72e9'

10-18 02:06:09 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by he0119** [comment]
看了一下 `96ced46e72e9` 这个脚本是 `nonebot_plugin_access_control` 插件的，如果你安装上这个插件应该就不会报错了。

**Comment by Xian0Grem** [comment]
> 看了一下 `96ced46e72e9` 这个脚本是 `nonebot_plugin_access_control` 插件的，如果你安装上这个插件应该就不会报错了。

感谢，项目跑起来了，我不用跑了
