### ISSUE TITLE
bug: 出现database is locked 

### ISSUE THREAD

**Issue by aknyzsd** [noneplugin/nonebot-plugin-chatrecorder#64]
在运行一段时间(可能是接收到某些特殊字符？）(具体原因未知）后出现接收到每条消息都出现database is locked 报错
![image](https://github.com/user-attachments/assets/f6e7a7ba-660f-4941-8692-5f9d951b5bf8)
![image](https://github.com/user-attachments/assets/bc10fec5-c55d-4c8e-8644-ca4303b6e8b3)
以上是报错信息（的一小部分），发现问题的时候上面触发问题的日志就已经被刷没了，抱歉qwq

**Comment by ElainaFanBoy** [comment]
+1，请问您解决了没

**Comment by aknyzsd** [comment]
> +1，请问您解决了没

并没有解决，但是没影响了
你是不是也装了话痨排行榜那个插件，貌似是那个插件的问题
（那个插件在我更新后orm启动不了）

**Comment by MeetWq** [comment]
#20
可以尝试将 sqlalchemy poolclass 设置为 StaticPool，不过这样在程序运行期间你的数据库文件都将被占用
参考：https://github.com/he0119/CoolQBot/blob/2c531498cae6252449ffd40d12b880c801d000ba/bot.py#L14

**Comment by ElainaFanBoy** [comment]
> #20 可以尝试将 sqlalchemy poolclass 设置为 StaticPool，不过这样在程序运行期间你的数据库文件都将被占用 参考：https://github.com/he0119/CoolQBot/blob/2c531498cae6252449ffd40d12b880c801d000ba/bot.py#L14

设置后
变成这样了![image](https://github.com/user-attachments/assets/84832f29-3e25-4992-ac78-95c8e15ec6b3)

**Comment by MeetWq** [comment]
> 设置后 变成这样了![image](https://private-user-images.githubusercontent.com/56375835/393819300-84832f29-3e25-4992-ac78-95c8e15ec6b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDY4OTMsIm5iZiI6MTczMzc0NjU5MywicGF0aCI6Ii81NjM3NTgzNS8zOTM4MTkzMDAtODQ4MzJmMjktM2UyNS00OTkyLWFjNzgtOTVjOGUxNWVjNmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEyMTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNmM1YjE0NThlMGFlMTkyMDVjODgzZDIxZDE2NTQwYzEzYjJmYmY4NGEzNDU2NzliYzJiY2JhYzJhMDgxNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MxxOBN9R4YzIZPCfddCoI7RI_mMmd7C1INQpY07pFb8)

大概率不是设置的原因，你可以改回去看有没有问题

**Comment by MeetWq** [comment]
> 改回去就没遇到过了

能不能发一下完整报错

**Comment by ElainaFanBoy** [comment]
> > 改回去就没遇到过了
> 
> 能不能发一下完整报错

我遇到过的报错大概如下
```
12-09 22:27:44 [ERROR] nonebot | Error when running EventPostProcessors
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\lastload\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 201, in handle_event
    await handle_event(self, event)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 560, in handle_event
    await _apply_event_postprocessors(bot, event, state, stack, dependency_cache)
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 209, in _apply_event_postprocessors
    await asyncio.gather(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\utils.py", line 236, in run_coro_with_catch
    return await coro
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_chatrecorder\adapters\onebot_v11.py", line 41, in record_recv_msg
    session_persist_id = await get_session_persist_id(session)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_session_orm\model.py", line 138, in get_session_persist_id
    await db_session.refresh(session_model)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 331, in refresh
    await greenlet_spawn(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\orm\session.py", line 3180, in refresh
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Could not refresh instance '<SessionModel at 0x15534d625f0>'
```

```
12-09 22:28:37 [ERROR] nonebot | Error when running EventPostProcessors
Traceback (most recent call last):
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 147, in execute
    self._adapt_connection._handle_exception(error)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 298, in _handle_exception
    raise error
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 136, in execute
    self._rows = deque(self.await_(_cursor.fetchall()))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\aiosqlite\cursor.py", line 76, in fetchall
    return await self._execute(self._cursor.fetchall)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\aiosqlite\core.py", line 132, in _execute
    return await future
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\aiosqlite\core.py", line 115, in run
    result = function()
sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\lastload\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 201, in handle_event
    await handle_event(self, event)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 560, in handle_event
    await _apply_event_postprocessors(bot, event, state, stack, dependency_cache)
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 209, in _apply_event_postprocessors
    await asyncio.gather(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\utils.py", line 236, in run_coro_with_catch
    return await coro
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_chatrecorder\adapters\onebot_v11.py", line 41, in record_recv_msg
    session_persist_id = await get_session_persist_id(session)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_session_orm\model.py", line 120, in get_session_persist_id
    if persist_id := (await db_session.scalars(statement)).one_or_none():
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 574, in scalars
    result = await self.execute(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 461, in execute
    result = await greenlet_spawn(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\orm\session.py", line 2362, in execute
    return self._execute_internal(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\orm\session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 147, in execute
    self._adapt_connection._handle_exception(error)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 298, in _handle_exception
    raise error
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 136, in execute
    self._rows = deque(self.await_(_cursor.fetchall()))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\aiosqlite\cursor.py", line 76, in fetchall
    return await self._execute(self._cursor.fetchall)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\aiosqlite\core.py", line 132, in _execute
    return await future
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\aiosqlite\core.py", line 115, in run
    result = function()
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
[SQL: SELECT nonebot_plugin_session_orm_sessionmodel.id
FROM nonebot_plugin_session_orm_sessionmodel
WHERE nonebot_plugin_session_orm_sessionmodel.bot_id = ? AND nonebot_plugin_session_orm_sessionmodel.bot_type = ? AND nonebot_plugin_session_orm_sessionmodel.platform = ? AND nonebot_plugin_session_orm_sessionmodel.level = ? AND nonebot_plugin_session_orm_sessionmodel.id1 = ? AND nonebot_plugin_session_orm_sessionmodel.id2 = ? AND nonebot_plugin_session_orm_sessionmodel.id3 = ?]
[parameters: ('3664798329', 'OneBot V11', 'qq', 2, '1551225461', '495328554', '')]
(Background on this error at: https://sqlalche.me/e/20/rvf5)
```
